extraction:
  cpp:
    after_prepare: 
      - python report.py 20
  cobol:
    after_prepare: 
      - python report.py 20
  csharp:
    after_prepare: 
      - python report.py 20
  java:
    after_prepare: 
      - python report.py 20
  javascript:
    after_prepare: 
      - python report.py 20
  python:
    after_prepare: 
      - python report.py 20
